# Generated by Django 4.0 on 2023-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPULoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.FloatField(null=True, verbose_name='CPU Load')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
